# Articles
https://keras.io/guides/transfer_learning/
https://keras.io/guides/training_with_built_in_methods/
https://www.youtube.com/watch?v=4umFSRPx-94&ab_channel=DigitalSreeni
https://www.tensorflow.org/guide/saved_model
https://github.com/UCSD-E4E/PyHa/blob/Microfaune_Retraining/Microfaune_Retraining-Copy1.ipynb

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import tensorflow as tf
from tensorflow import keras

In [3]:
train = True

## Load in BirdNET-Analyzer Model

In [4]:
# path to model folder, should have assets/variables/frozen pb graphs
path_to_saved_model = "./checkpoints/V2.1/BirdNET_GLOBAL_2K_V2.1_Model"

In [5]:
model = keras.models.load_model(path_to_saved_model)

In [6]:
model.compile(optimizer="adam",
              loss="binary_crossentropy",
              metrics=['accuracy'])

In [7]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
INPUT (InputLayer)              [(None, 144000)]     0                                            
__________________________________________________________________________________________________
ADVANCED_SPEC1 (LinearSpecLayer (None, 128, 513, 1)  1           INPUT[0][0]                      
__________________________________________________________________________________________________
BNORM_SPEC_NOQUANT (BatchNormal (None, 128, 513, 1)  4           ADVANCED_SPEC1[0][0]             
__________________________________________________________________________________________________
CONV_0 (Conv2D)                 (None, 64, 257, 30)  960         BNORM_SPEC_NOQUANT[0][0]         
______________________________________________________________________________________________

## Preprocess and load data
According to `config.py` and `checkpoints/README.md` for V2.1:  
- Model training input size: 144000 = 48000 x 3 = sample rate x num chunks  
- Model training output size: 2434 = 2424 bird classes + 10 non-event classes
- Visualize using [Netron](https://netron.app/)

In [90]:
import librosa

def splitSignal(sig, rate, overlap, seconds=3.0, minlen=1.5):

    # Split signal with overlap
    sig_splits = []
    for i in range(0, len(sig), int((seconds - overlap) * rate)):
        split = sig[i:i + int(seconds * rate)]

        # End of signal?
        if len(split) < int(minlen * rate):
            break
        
        # Signal chunk too short? Fill with zeros.
        if len(split) < int(rate * seconds):
            temp = np.zeros((int(rate * seconds)))
            temp[:len(split)] = split
            split = temp
        
        sig_splits.append(split)

    return sig_splits

def readAudioData(path, overlap, sample_rate=48000):

    #print('READING AUDIO DATA...', end=' ', flush=True)

    # Open file with librosa (uses ffmpeg or libav)
    try:
        sig, rate = librosa.load(path, sr=sample_rate, mono=True, res_type='kaiser_fast')
        clip_length = librosa.get_duration(y=sig, sr=rate)
    except:
        return 0
    # Split audio into 3-second chunks
    chunks = splitSignal(sig, rate, overlap)

    print('DONE! READ', str(len(chunks)), 'CHUNKS.')

    return chunks, clip_length

import pandas as pd
import numpy as np


#TODO Add mutliple species support for ROC curves 
def annotation_chunker_no_duplicates(kaleidoscope_df, chunk_length, include_no_bird=False, bird=None):
    """
    Function that converts a Kaleidoscope-formatted Dataframe containing 
    annotations to uniform chunks of chunk_length. If there
    are mutliple bird species in the same clip, this function creates chunks
    for the more confident bird species.

    Note: if all or part of an annotation covers the last < chunk_length
    seconds of a clip it will be ignored. If two annotations overlap in 
    the same 3 second chunk, both are represented in that chunk
    Args:
        kaleidoscope_df (Dataframe)
            - Dataframe of annotations in kaleidoscope format

        chunk_length (int)
            - duration to set all annotation chunks
    Returns:
        Dataframe of labels with chunk_length duration 
        (elements in "OFFSET" are divisible by chunk_length).
    """

    #Init list of clips to cycle through and output dataframe
    #kaleidoscope_df["FILEPATH"] =  kaleidoscope_df["FOLDER"] + kaleidoscope_df["IN FILE"] 
    kaleidoscope_df['FILEPATH'] = kaleidoscope_df.loc[:,['FOLDER','IN FILE']].sum(axis=1)
    clips = kaleidoscope_df["FILEPATH"].unique()
    df_columns = {'FOLDER': 'str', 'IN FILE' :'str', 'CLIP LENGTH' : 'float64', 'CHANNEL' : 'int64', 'OFFSET' : 'float64',
                'DURATION' : 'float64', 'SAMPLE RATE' : 'int64','MANUAL ID' : 'str'}
    output_df = pd.DataFrame({c: pd.Series(dtype=t) for c, t in df_columns.items()})
    
    # going through each clip
    for clip in clips:
        clip_df = kaleidoscope_df[kaleidoscope_df["FILEPATH"] == clip]
        path = clip_df["FOLDER"].unique()[0]
        file = clip_df["IN FILE"].unique()[0]
        birds = clip_df["MANUAL ID"].unique()
        sr = clip_df["SAMPLE RATE"].unique()[0]
        clip_len = clip_df["CLIP LENGTH"].unique()[0]

        # quick data sanitization to remove very short clips
        # do not consider any chunk that is less than chunk_length
        if clip_len < chunk_length:
            continue
        potential_annotation_count = int(clip_len)//int(chunk_length)

        # going through each species that was ID'ed in the clip
        arr_len = int(clip_len*1000)
        species_df = clip_df#[clip_df["MANUAL ID"] == bird]
        human_arr = np.zeros((arr_len))
        # looping through each annotation
        #print("========================================")
        for annotation in species_df.index:
            #print(species_df["OFFSET"][annotation])
            minval = int(round(species_df["OFFSET"][annotation] * 1000, 0))
            # Determining the end of a human label
            maxval = int(
                round(
                    (species_df["OFFSET"][annotation] +
                        species_df["DURATION"][annotation]) *
                    1000,
                    0))
            # Placing the label relative to the clip
            human_arr[minval:maxval] = 1
        # performing the chunk isolation technique on the human array

        for index in range(potential_annotation_count):
            #print("=======================")
            #print("-----------------------------------------")
            #print(index)
            chunk_start = index * (chunk_length*1000)
            chunk_end = min((index+1)*chunk_length*1000,arr_len)
            chunk = human_arr[int(chunk_start):int(chunk_end)]
            if max(chunk) >= 0.5:
                #Get row data
                row = pd.DataFrame(index = [0])
                annotation_start = chunk_start / 1000

                #Handle birdnet output edge case
                #print("-------------------------------------------")
                #print(sum(clip_df["DURATION"] == 3))
                #print(sum(clip_df["DURATION"] == 3)/clip_df.shape[0])
                #print("-------------------------------------------")
                if(sum(clip_df["DURATION"] == 3)/clip_df.shape[0] == 1):
                    #print("Processing here duration")
                    overlap = (clip_df["OFFSET"]+0.5 >= (annotation_start)) & (clip_df["OFFSET"]-0.5 <= (annotation_start))
                    annotation_df = clip_df[overlap]
                    #print(annotation_start, np.array(clip_df["OFFSET"]), overlap)
                    #print(annotation_df)
                else:
                    #print("Processing here")
                    overlap = is_overlap(clip_df["OFFSET"], clip_df["OFFSET"] + clip_df["DURATION"], annotation_start, annotation_start + chunk_length)
                    #print(overlap)
                    annotation_df = clip_df[overlap]
                    #print(annotation_df)
                
                #updating the dictionary
                if ('CONFIDENCE' in clip_df.columns):
                    annotation_df = annotation_df.sort_values(by="CONFIDENCE", ascending=False)
                    row["CONFIDENCE"] = annotation_df.iloc[0]["CONFIDENCE"]
                else:
                    #The case of manual id, or there is an annotation with no known confidence
                    row["CONFIDENCE"] = 1
                row["FOLDER"] = path
                row["IN FILE"] = file
                row["CLIP LENGTH"] = clip_len
                row["OFFSET"] = annotation_start
                row["DURATION"] = chunk_length
                row["SAMPLE RATE"] = sr
                row["MANUAL ID"] = annotation_df.iloc[0]["MANUAL ID"] 
                row["CHANNEL"] = 0
                output_df = pd.concat([output_df,row], ignore_index=True)
            elif(include_no_bird):
                #print(max(chunk))
                #Get row data
                row = pd.DataFrame(index = [0])
                annotation_start = chunk_start / 1000

                #updating the dictionary
                row["CONFIDENCE"] = 0
                row["FOLDER"] = path
                row["IN FILE"] = file
                row["CLIP LENGTH"] = clip_len
                row["OFFSET"] = annotation_start
                row["DURATION"] = chunk_length
                row["SAMPLE RATE"] = sr
                row["MANUAL ID"] = "no bird"
                row["CHANNEL"] = 0
                output_df = pd.concat([output_df,row], ignore_index=True)
    
    return output_df


def is_overlap(offset_df, end_df, chunk_start, chunk_end):
    is_both_before = (chunk_end < offset_df) & (chunk_start < offset_df)
    is_both_after = (end_df < chunk_end) & (end_df < chunk_start)
    return (~is_both_before) & (~is_both_after)
    
    
    interval = pd.Interval(left=offset_df, right=end_df)
    print(interval)


def split_save_files(dataframe_of_data):
    chunked_df = annotation_chunker_no_duplicates(dataframe_of_data, 3, include_no_bird=True)
    
    
    chunked_df.apply()
    



In [91]:
chunks,clip_length  = readAudioData("./Data/code-testing/XC628854 - Yellow-olive Flatbill - Tolmomyias sulphurescens.mp3", 0, sample_rate=48000)

DONE! READ 39 CHUNKS.


In [92]:
import pandas as pd
data = pd.read_csv("C:/Users/Siloux/Desktop/E4E/passive-acoustic-biodiversity/TweetyNET/cosmos_data/cosmos_random_sample_processing/automated_cosmos_tweety_to_birdnet.csv")
chunked_df = annotation_chunker_no_duplicates(data, 3, include_no_bird=True)
chunked_df

FOLDER                                            IN FILE  \
0      .\..\Cosmos_data\  XC100027 - Southern Nightingale-Wren - Microce...   
1      .\..\Cosmos_data\  XC100027 - Southern Nightingale-Wren - Microce...   
2      .\..\Cosmos_data\  XC100027 - Southern Nightingale-Wren - Microce...   
3      .\..\Cosmos_data\  XC100027 - Southern Nightingale-Wren - Microce...   
4      .\..\Cosmos_data\  XC100027 - Southern Nightingale-Wren - Microce...   
...                  ...                                                ...   
39712  .\..\Cosmos_data\  XC9881 - Blue-grey Tanager - Thraupis episcopu...   
39713  .\..\Cosmos_data\  XC9881 - Blue-grey Tanager - Thraupis episcopu...   
39714  .\..\Cosmos_data\  XC9881 - Blue-grey Tanager - Thraupis episcopu...   
39715  .\..\Cosmos_data\  XC9881 - Blue-grey Tanager - Thraupis episcopu...   
39716  .\..\Cosmos_data\  XC99284 - Slate-throated Whitestart - Myioboru...   

       CLIP LENGTH  CHANNEL  OFFSET  DURATION  SAMPLE RATE  \
0        81.528167        0     0.0       3.0        48000   
1        81.528167        0     3.0       3.0        48000   
2        81.528167        0     6.0       3.0        48000   
3        81.528167        0     9.0       3.0        48000   
4        81.528167        0    12.0       3.0        48000   
...            ...      ...     ...       ...          ...   
39712    14.700021        0     0.0       3.0        48000   
39713    14.700021        0     3.0       3.0        48000   
39714    14.700021        0     6.0       3.0        48000   
39715    14.700021        0     9.0       3.0        48000   
39716     3.369813        0     0.0       3.0        48000   

                      MANUAL ID  CONFIDENCE  
0      Microcerculus marginatus    0.155038  
1          Centropus celebensis    0.020985  
2              Meliphaga notata    0.027436  
3      Microcerculus marginatus    0.331647  
4        Sciaphylax hemimelaena    0.017806  
...                         ...         ...  
39712        Thraupis episcopus    0.146423  
39713   Pyrrhocorax pyrrhocorax    0.042745  
39714           Thraupis sayaca    0.108350  
39715                   no bird    0.000000  
39716    Ptilorrhoa leucosticta    0.033264  

[39717 rows x 9 columns]

In [98]:
chunked_df["FOLDER"] = "./Data/code-testing/"

In [128]:
species_of_interests = list(np.unique(chunked_df["MANUAL ID"]))
chunked_df["y"] = chunked_df["MANUAL ID"].apply(lambda x: species_of_interests.index(x))
chunked_df

X = []
Y = []
UID = []

#assume df is chunked
for file in np.unique(chunked_df["IN FILE"]):
    file_df = chunked_df[chunked_df["IN FILE"] == file]
    #print((file_df["FOLDER"] + file_df["IN FILE"]).iloc[0])
    try:
        chunks, clip_length = readAudioData((file_df["FOLDER"] + file_df["IN FILE"]).iloc[0], 0, sample_rate=48000)
    except:
        continue
    offset = 0
    for c in range(len(chunks)):
        offset = c * 3
        chunk_df = file_df[file_df["OFFSET"] == offset].sample(1)
        if (chunk_df.empty):
            break
        # Add to batch
        X.append(chunks[c])
        Y.append(chunk_df["y"].iloc[0])
        UID.append(chunk_df.index[0])

        
X, Y, UID

DONE! READ 39 CHUNKS.


([array([ 0.        ,  0.        ,  0.        , ..., -0.00122339,
         -0.00041645, -0.00049684], dtype=float32),
  array([-0.00054962,  0.00087783,  0.00216126, ..., -0.00060256,
          0.00029474,  0.00108685], dtype=float32),
  array([ 0.00134224,  0.00134801,  0.00113327, ..., -0.00163486,
         -0.00103791, -0.00083348], dtype=float32),
  array([-0.00030538,  0.00077696,  0.00186265, ...,  0.00262075,
          0.00142806,  0.00146308], dtype=float32),
  array([0.00219837, 0.0019769 , 0.00159717, ..., 0.00185045, 0.00194336,
         0.00275659], dtype=float32),
  array([ 0.00201688, -0.00056329, -0.0024023 , ...,  0.01364738,
          0.0114228 ,  0.0069463 ], dtype=float32),
  array([ 4.3002030e-04, -8.1077758e-03, -1.5722346e-02, ...,
          6.3503889e-04,  9.9656964e-04,  6.2260133e-06], dtype=float32),
  array([-0.00119472, -0.00186244, -0.00263428, ...,  0.00135381,
          0.0013627 ,  0.00026072], dtype=float32),
  array([-0.00036479, -0.00023118, -0.001161

In [129]:
dataset = {"X":X, "Y": Y, "uids": UID}
inds = [i for i, x in enumerate(dataset["X"])]
X = np.array([dataset["X"][i].transpose() for i in inds])
Y = np.array([int(dataset["Y"][i]) for i in inds])
uids = [dataset["uids"][i] for i in inds]
X, Y, uids

(array([[ 0.        ,  0.        ,  0.        , ..., -0.00122339,
         -0.00041645, -0.00049684],
        [-0.00054962,  0.00087783,  0.00216126, ..., -0.00060256,
          0.00029474,  0.00108685],
        [ 0.00134224,  0.00134801,  0.00113327, ..., -0.00163486,
         -0.00103791, -0.00083348],
        ...,
        [-0.00024435,  0.00049659,  0.00046859, ..., -0.00094429,
          0.00212899,  0.00373677],
        [ 0.00430433,  0.00473556,  0.0036698 , ..., -0.00256654,
         -0.003216  , -0.00241336],
        [-0.00173771, -0.00150881, -0.00052083, ..., -0.00044005,
         -0.00200539, -0.00282954]], dtype=float32),
 array([2560, 2560, 2560, 2560, 2560, 2560, 2560, 2560, 2560, 2560, 2560,
        2560, 2333, 2560, 2560, 2560, 2560, 2560, 2560, 2560, 2560, 2333,
        2560, 2560, 2560, 2560, 2560, 2560, 2560, 2560, 2560, 2560, 2560,
        2560, 2560, 2560, 2560, 2560, 2560]),
 [33042,
  33043,
  33044,
  33045,
  33046,
  33047,
  33048,
  33049,
  33050,
  33051,


In [130]:
from sklearn.model_selection import StratifiedShuffleSplit
def split_dataset(X, Y, test_size=0.2, random_state=0):
    split_generator = StratifiedShuffleSplit(n_splits=1, test_size=test_size, random_state=random_state)
    ind_train, ind_test = next(split_generator.split(X, Y))
    X_train, X_test = X[ind_train], X[ind_test]
    Y_train, Y_test = Y[ind_train], Y[ind_test]
    return ind_train, ind_test

ind_train_val, ind_test = split_dataset(X, Y)


In [131]:
ind_train_val, ind_test

(array([35, 26, 14, 15, 38, 34, 30, 28, 32, 18,  6, 31, 16, 33, 36, 10, 17,
        29, 13, 24,  8, 27, 22,  7,  5,  2, 25,  1, 11, 12, 21],
       dtype=int64),
 array([ 9, 19, 37,  4,  0, 23,  3, 20], dtype=int64))

In [132]:
from collections import Counter
X_train, Y_train = X[ind_train_val, np.newaxis], Y[ind_train_val]
X_test,  Y_test =  X[ind_test, np.newaxis], Y[ind_val]          
                    

print("Training set: ", Counter(Y_train))
print("Test set: ", Counter(Y_test))
print("Validation set: ", Counter(Y_val))
#very imbalanced dataset

Training set:  Counter({2560: 29, 2333: 2})
Test set:  Counter({2560: 3, 2333: 1})
Validation set:  Counter({2560: 3, 2333: 1})


In [135]:
species_of_interests

['Abroscopus albogularis',
 'Acanthis flammea',
 'Acanthisitta chloris',
 'Acanthiza inornata',
 'Acanthiza lineata',
 'Acanthiza nana',
 'Acanthiza pusilla',
 'Acanthiza uropygialis',
 'Accipiter badius',
 'Accipiter cooperii',
 'Accipiter gentilis',
 'Accipiter minullus',
 'Accipiter poliogaster',
 'Accipiter superciliosus',
 'Accipiter tachiro',
 'Accipiter trivirgatus',
 'Aceros nipalensis',
 'Acridotheres cristatellus',
 'Acrocephalus arundinaceus',
 'Acrocephalus dumetorum',
 'Acrocephalus palustris',
 'Acrocephalus schoenobaenus',
 'Acrocephalus stentoreus',
 'Acropternis orthonyx',
 'Actenoides concretus',
 'Actenoides lindsayi',
 'Actitis hypoleucos',
 'Actitis macularius',
 'Adelomyia melanogenys',
 'Aegithalos caudatus',
 'Aegithalos niveogularis',
 'Aegithina viridissima',
 'Aegolius acadicus',
 'Aegotheles cristatus',
 'Aeronautes andecolus',
 'Aethopyga christinae',
 'Aethopyga ignicauda',
 'Aethopyga siparaja',
 'Aethopyga temminckii',
 'Aethopyga vigorsii',
 'Agapornis 

## Retrain Model

In [150]:
from datetime import datetime
class DataGenerator(keras.utils.Sequence):
    def __init__(self, X, Y, batch_size=32):
        self.X = X
        self.Y = Y
        self.n = len(Y)
        self.batch_size = batch_size
        self.shuffle()
        
    def __len__(self):
        return int(np.floor(self.n)/self.batch_size)
    
    def __getitem__(self, index):
        batch_inds = self.inds[self.batch_size*index:self.batch_size*(index+1)]
        self.counter += self.batch_size
        if self.counter >= self.n:
            self.shuffle()
        print(self.X[batch_inds, ...][0], self.Y[batch_inds][0])
        return tf.convert_to_tensor(self.X[batch_inds, ...][0]), tf.convert_to_tensor(self.Y[batch_inds][0])
    
    def shuffle(self):
        self.inds = np.random.permutation(self.n)
        self.counter = 0
# if train:

In [151]:
# microfaune training script
if train:
    optimizer = keras.optimizers.Adam(lr=0.001)
    model.compile(optimizer=optimizer,
                  loss='binary_crossentropy',
                  metrics=['accuracy', keras.metrics.FalseNegatives()])

    alpha = 0.5
    batch_size = 1
    date_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    data_generator = DataGenerator(X_train, Y_train, batch_size)
    
    micro_callbacks = [
        keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.2,
                                  patience=5, min_lr=1e-5),
        keras.callbacks.ModelCheckpoint('microfaune-' + date_str +'-{epoch:02d}.h5',
                                  save_weights_only=False)
    ]
    
    history = model.fit(data_generator, steps_per_epoch=100, epochs=10,
                                  validation_data=(X_test, Y_test),
                                  class_weight={0: alpha, 1: 1-alpha},
                                  callbacks=micro_callbacks, verbose=1)
    
    model.save(f"model-{date_str}")
    model.save_weights(f"model_weights-{date_str}.h5")

[[ 0.00088874 -0.0005915  -0.00233662 ...  0.00438146  0.002564
   0.00128405]] 2560
Epoch 1/10


ValueError: in user code:

    C:\Users\Siloux\.conda\envs\species-id\lib\site-packages\tensorflow\python\keras\engine\training.py:806 train_function  *
        return step_function(self, iterator)
    C:\Users\Siloux\.conda\envs\species-id\lib\site-packages\tensorflow\python\keras\engine\training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\Siloux\.conda\envs\species-id\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\Siloux\.conda\envs\species-id\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\Siloux\.conda\envs\species-id\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\Siloux\.conda\envs\species-id\lib\site-packages\tensorflow\python\keras\engine\training.py:789 run_step  **
        outputs = model.train_step(data)
    C:\Users\Siloux\.conda\envs\species-id\lib\site-packages\tensorflow\python\keras\engine\training.py:749 train_step
        y, y_pred, sample_weight, regularization_losses=self.losses)
    C:\Users\Siloux\.conda\envs\species-id\lib\site-packages\tensorflow\python\keras\engine\compile_utils.py:212 __call__
        batch_dim = array_ops.shape(y_t)[0]
    C:\Users\Siloux\.conda\envs\species-id\lib\site-packages\tensorflow\python\util\dispatch.py:201 wrapper
        return target(*args, **kwargs)
    C:\Users\Siloux\.conda\envs\species-id\lib\site-packages\tensorflow\python\ops\array_ops.py:1024 _slice_helper
        name=name)
    C:\Users\Siloux\.conda\envs\species-id\lib\site-packages\tensorflow\python\util\dispatch.py:201 wrapper
        return target(*args, **kwargs)
    C:\Users\Siloux\.conda\envs\species-id\lib\site-packages\tensorflow\python\ops\array_ops.py:1196 strided_slice
        shrink_axis_mask=shrink_axis_mask)
    C:\Users\Siloux\.conda\envs\species-id\lib\site-packages\tensorflow\python\ops\gen_array_ops.py:10352 strided_slice
        shrink_axis_mask=shrink_axis_mask, name=name)
    C:\Users\Siloux\.conda\envs\species-id\lib\site-packages\tensorflow\python\framework\op_def_library.py:744 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    C:\Users\Siloux\.conda\envs\species-id\lib\site-packages\tensorflow\python\framework\func_graph.py:593 _create_op_internal
        compute_device)
    C:\Users\Siloux\.conda\envs\species-id\lib\site-packages\tensorflow\python\framework\ops.py:3485 _create_op_internal
        op_def=op_def)
    C:\Users\Siloux\.conda\envs\species-id\lib\site-packages\tensorflow\python\framework\ops.py:1975 __init__
        control_input_ops, op_def)
    C:\Users\Siloux\.conda\envs\species-id\lib\site-packages\tensorflow\python\framework\ops.py:1815 _create_c_op
        raise ValueError(str(e))

    ValueError: slice index 0 of dimension 0 out of bounds. for '{{node strided_slice}} = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1](Shape, strided_slice/stack, strided_slice/stack_1, strided_slice/stack_2)' with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <0>, input[2] = <1>, input[3] = <1>.
