In [1]:
import pandas as pd


In [3]:
data = pd.read_csv("C:/Users/Siloux/Downloads/xc_embeddings_hdbscan_preds (1).csv")

In [32]:
visualization_data  = data[["MANUAL ID", "HDBSCAN PREDICTIONS"]]
visualization_data = visualization_data.groupby("MANUAL ID")["HDBSCAN PREDICTIONS"].apply(list)
visualization_data

MANUAL ID
Aburria aburri                     [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 726]
Accipiter bicolor                                                               [-1]
Accipiter striatus                                                              [-1]
Actitis macularius                 [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -...
Adelomyia melanogenys              [89, 89, 89, 89, 89, 89, 89, 26, 26, 26, 26, 2...
                                                         ...                        
Xiphocolaptes promeropirhynchus    [176, 176, 176, 176, 176, 176, 176, -1, 249, 2...
Xiphorhynchus guttatus             [473, -1, 473, -1, -1, 473, -1, 640, 640, 640,...
Zenaida auriculata                 [-1, 782, 782, 782, 782, -1, -1, 782, -1, 782,...
Zentrygon frenata                  [-1, 990, 990, 990, 990, 990, 990, 990, 990, 9...
Zonotrichia capensis               [185, 185, 185, -1, -1, -1, 185, 185, -1, 185,...
Name: HDBSCAN PREDICTIONS, Length: 476, dtype: object

In [48]:
data[data["HDBSCAN PREDICTIONS"] == 993]

Unnamed: 0                           IN FILE                    PATH  \
3375        3381  Crypturellus-obsoletus-47234.wav  ./input/xc_embeddings/   
3382        3388  Crypturellus-obsoletus-47234.wav  ./input/xc_embeddings/   
3383        3389  Crypturellus-obsoletus-47234.wav  ./input/xc_embeddings/   
3384        3390  Crypturellus-obsoletus-47234.wav  ./input/xc_embeddings/   
3385        3391  Crypturellus-obsoletus-47234.wav  ./input/xc_embeddings/   

      START   END         0         1         2         3         4  ...  \
3375   15.0  18.0  0.658197  0.194323  0.674550  0.201408  0.141349  ...   
3382   36.0  39.0  0.985208  0.169447  0.700885  0.230946  0.132148  ...   
3383   39.0  42.0  0.954158  0.250140  0.852352  0.221314  0.272380  ...   
3384   42.0  45.0  1.259056  0.270644  0.934913  0.323397  0.183130  ...   
3385   45.0  48.0  0.637810  0.209537  0.483403  0.280217  0.221966  ...   

           415       416       417       418       419  MANUAL ID  \
3375  0.217870  0.532509  0.216953  0.404182  0.197420    No bird   
3382  0.102340  0.555290  0.244456  0.509709  0.193834    No bird   
3383  0.454187  0.646374  0.277019  0.520869  0.209447    No bird   
3384  0.364674  0.633804  0.347630  0.557019  0.215658    No bird   
3385  0.213762  0.533080  0.387121  0.605499  0.209428    No bird   

                FILE SPECIES  HDBSCAN PREDICTIONS  HDBSCAN PROBABILITIES  \
3375  Crypturellus obsoletus                  993                    1.0   
3382  Crypturellus obsoletus                  993                    1.0   
3383  Crypturellus obsoletus                  993                    1.0   
3384  Crypturellus obsoletus                  993                    1.0   
3385  Crypturellus obsoletus                  993                    1.0   

      MANUAL ID NUMS  
3375             287  
3382             287  
3383             287  
3384             287  
3385             287  

[5 rows x 430 columns]

In [44]:
clusters_count = max(data["HDBSCAN PREDICTIONS"])
print(clusters_count)
one_hot = pd.DataFrame(columns=np.append(np.arange(-1, clusters_count+1), "MANUAL ID")).set_index("MANUAL ID")

def convert_counts_to_one_hot(index):    
    values, counts = np.unique(visualization_data.loc[index], return_counts=True)
    values, counts
    temp_one_hot_array = np.zeros(clusters_count + 2)
    print(len(temp_one_hot_array))
    for i in range(len(values)):
        one_hot_index = values[i] + 1
        temp_one_hot_array[one_hot_index] = counts[i]
    return temp_one_hot_array

for index, row in visualization_data.iteritems():
    one_hot.loc[index] = convert_counts_to_one_hot(index)

993
995
0
[ -1 726]
2
0
1
[ -1 726]
2
727
995
0
[-1]
1
0
995
0
[-1]
1
0
995
0
[-1]
1
0
995
0
[20 26 89]
3
21
1
[20 26 89]
3
27
2
[20 26 89]
3
90
995
0
[ -1 421]
2
0
1
[ -1 421]
2
422
995
0
[ -1 270]
2
0
1
[ -1 270]
2
271
995
0
[726]
1
727
995
0
[ -1 757 828 882]
4
0
1
[ -1 757 828 882]
4
758
2
[ -1 757 828 882]
4
829
3
[ -1 757 828 882]
4
883
995
0
[ -1 581]
2
0
1
[ -1 581]
2
582
995
0
[ -1 516]
2
0
1
[ -1 516]
2
517
995
0
[ -1 411]
2
0
1
[ -1 411]
2
412
995
0
[ -1 267 827 882]
4
0
1
[ -1 267 827 882]
4
268
2
[ -1 267 827 882]
4
828
3
[ -1 267 827 882]
4
883
995
0
[-1 34]
2
0
1
[-1 34]
2
35
995
0
[125 408]
2
126
1
[125 408]
2
409
995
0
[ -1 710 855]
3
0
1
[ -1 710 855]
3
711
2
[ -1 710 855]
3
856
995
0
[ -1 240 333]
3
0
1
[ -1 240 333]
3
241
2
[ -1 240 333]
3
334
995
0
[-1]
1
0
995
0
[ -1 486 488 489]
4
0
1
[ -1 486 488 489]
4
487
2
[ -1 486 488 489]
4
489
3
[ -1 486 488 489]
4
490
995
0
[-1]
1
0
995
0
[ -1 156 382]
3
0
1
[ -1 156 382]
3
157
2
[ -1 156 382]
3
383
995
0
[364 367 596]
3


995
0
[-1  8]
2
0
1
[-1  8]
2
9
995
0
[ -1 479 480 481]
4
0
1
[ -1 479 480 481]
4
480
2
[ -1 479 480 481]
4
481
3
[ -1 479 480 481]
4
482
995
0
[-1]
1
0
995
0
[-1]
1
0
995
0
[161 268]
2
162
1
[161 268]
2
269
995
0
[-1]
1
0
995
0
[ -1 238 901]
3
0
1
[ -1 238 901]
3
239
2
[ -1 238 901]
3
902
995
0
[-1]
1
0
995
0
[ -1 583 584 804]
4
0
1
[ -1 583 584 804]
4
584
2
[ -1 583 584 804]
4
585
3
[ -1 583 584 804]
4
805
995
0
[ -1 348]
2
0
1
[ -1 348]
2
349
995
0
[ -1 194]
2
0
1
[ -1 194]
2
195
995
0
[ -1 181 893]
3
0
1
[ -1 181 893]
3
182
2
[ -1 181 893]
3
894
995
0
[ -1 636]
2
0
1
[ -1 636]
2
637
995
0
[-1]
1
0
995
0
[ -1 572 765]
3
0
1
[ -1 572 765]
3
573
2
[ -1 572 765]
3
766
995
0
[-1]
1
0
995
0
[ -1 296 357 455]
4
0
1
[ -1 296 357 455]
4
297
2
[ -1 296 357 455]
4
358
3
[ -1 296 357 455]
4
456
995
0
[ -1 297]
2
0
1
[ -1 297]
2
298
995
0
[-1]
1
0
995
0
[93]
1
94
995
0
[ -1  18 138]
3
0
1
[ -1  18 138]
3
19
2
[ -1  18 138]
3
139
995
0
[ -1 402]
2
0
1
[ -1 402]
2
403
995
0
[-1]
1
0
995
0
[ -1 59

 976 979 983 984 985 986 988 989 991 992 993]
317
176
23
[ -1   0  10  44  49  50  55  74  80  82  84  87  88 103 122 131 133 138
 143 159 170 172 175 196 198 199 210 213 225 227 228 229 230 238 239 250
 254 261 270 275 283 288 299 303 322 325 334 340 343 345 351 352 357 362
 363 368 369 370 372 375 377 379 380 382 383 384 385 393 394 395 404 405
 407 412 415 418 420 421 422 424 430 431 435 441 445 446 447 454 455 456
 457 462 471 473 474 475 478 481 485 486 488 490 495 497 498 500 506 507
 508 511 514 517 521 526 528 529 530 531 533 534 537 538 540 541 544 547
 553 554 556 557 561 573 578 582 593 595 598 599 603 605 606 607 622 623
 627 629 632 638 639 647 651 653 654 655 659 664 667 669 672 675 679 688
 693 694 695 697 698 699 700 701 702 703 704 705 706 707 708 711 716 718
 721 722 723 724 726 729 730 732 733 734 735 737 739 740 741 742 744 748
 749 751 752 753 756 758 761 762 763 765 766 768 772 774 775 776 778 779
 780 782 784 785 793 796 798 799 800 803 806 807 815 816 817 818 82

 976 979 983 984 985 986 988 989 991 992 993]
317
640
149
[ -1   0  10  44  49  50  55  74  80  82  84  87  88 103 122 131 133 138
 143 159 170 172 175 196 198 199 210 213 225 227 228 229 230 238 239 250
 254 261 270 275 283 288 299 303 322 325 334 340 343 345 351 352 357 362
 363 368 369 370 372 375 377 379 380 382 383 384 385 393 394 395 404 405
 407 412 415 418 420 421 422 424 430 431 435 441 445 446 447 454 455 456
 457 462 471 473 474 475 478 481 485 486 488 490 495 497 498 500 506 507
 508 511 514 517 521 526 528 529 530 531 533 534 537 538 540 541 544 547
 553 554 556 557 561 573 578 582 593 595 598 599 603 605 606 607 622 623
 627 629 632 638 639 647 651 653 654 655 659 664 667 669 672 675 679 688
 693 694 695 697 698 699 700 701 702 703 704 705 706 707 708 711 716 718
 721 722 723 724 726 729 730 732 733 734 735 737 739 740 741 742 744 748
 749 751 752 753 756 758 761 762 763 765 766 768 772 774 775 776 778 779
 780 782 784 785 793 796 798 799 800 803 806 807 815 816 817 818 8

 976 979 983 984 985 986 988 989 991 992 993]
317
923
274
[ -1   0  10  44  49  50  55  74  80  82  84  87  88 103 122 131 133 138
 143 159 170 172 175 196 198 199 210 213 225 227 228 229 230 238 239 250
 254 261 270 275 283 288 299 303 322 325 334 340 343 345 351 352 357 362
 363 368 369 370 372 375 377 379 380 382 383 384 385 393 394 395 404 405
 407 412 415 418 420 421 422 424 430 431 435 441 445 446 447 454 455 456
 457 462 471 473 474 475 478 481 485 486 488 490 495 497 498 500 506 507
 508 511 514 517 521 526 528 529 530 531 533 534 537 538 540 541 544 547
 553 554 556 557 561 573 578 582 593 595 598 599 603 605 606 607 622 623
 627 629 632 638 639 647 651 653 654 655 659 664 667 669 672 675 679 688
 693 694 695 697 698 699 700 701 702 703 704 705 706 707 708 711 716 718
 721 722 723 724 726 729 730 732 733 734 735 737 739 740 741 742 744 748
 749 751 752 753 756 758 761 762 763 765 766 768 772 774 775 776 778 779
 780 782 784 785 793 796 798 799 800 803 806 807 815 816 817 818 8

995
0
[ -1 109]
2
0
1
[ -1 109]
2
110
995
0
[ -1 154 306]
3
0
1
[ -1 154 306]
3
155
2
[ -1 154 306]
3
307
995
0
[ -1  95 487]
3
0
1
[ -1  95 487]
3
96
2
[ -1  95 487]
3
488
995
0
[ -1 539 769]
3
0
1
[ -1 539 769]
3
540
2
[ -1 539 769]
3
770
995
0
[ -1 716 719 720]
4
0
1
[ -1 716 719 720]
4
717
2
[ -1 716 719 720]
4
720
3
[ -1 716 719 720]
4
721
995
0
[ -1 897 898 951 981 982 984]
7
0
1
[ -1 897 898 951 981 982 984]
7
898
2
[ -1 897 898 951 981 982 984]
7
899
3
[ -1 897 898 951 981 982 984]
7
952
4
[ -1 897 898 951 981 982 984]
7
982
5
[ -1 897 898 951 981 982 984]
7
983
6
[ -1 897 898 951 981 982 984]
7
985
995
0
[ -1 303]
2
0
1
[ -1 303]
2
304
995
0
[ 97 606]
2
98
1
[ 97 606]
2
607
995
0
[ -1 474]
2
0
1
[ -1 474]
2
475
995
0
[ -1 842 843 845 846]
5
0
1
[ -1 842 843 845 846]
5
843
2
[ -1 842 843 845 846]
5
844
3
[ -1 842 843 845 846]
5
846
4
[ -1 842 843 845 846]
5
847
995
0
[ -1 160 609 612 613]
5
0
1
[ -1 160 609 612 613]
5
161
2
[ -1 160 609 612 613]
5
610
3
[ -1 160 609 612 613]
5


995
0
[ -1 340 343 344]
4
0
1
[ -1 340 343 344]
4
341
2
[ -1 340 343 344]
4
344
3
[ -1 340 343 344]
4
345
995
0
[ -1 118 794 795 818 824 885]
7
0
1
[ -1 118 794 795 818 824 885]
7
119
2
[ -1 118 794 795 818 824 885]
7
795
3
[ -1 118 794 795 818 824 885]
7
796
4
[ -1 118 794 795 818 824 885]
7
819
5
[ -1 118 794 795 818 824 885]
7
825
6
[ -1 118 794 795 818 824 885]
7
886
995
0
[ -1 315 338 591]
4
0
1
[ -1 315 338 591]
4
316
2
[ -1 315 338 591]
4
339
3
[ -1 315 338 591]
4
592
995
0
[ -1 374]
2
0
1
[ -1 374]
2
375
995
0
[-1 98]
2
0
1
[-1 98]
2
99
995
0
[218 423]
2
219
1
[218 423]
2
424
995
0
[ -1 114 284]
3
0
1
[ -1 114 284]
3
115
2
[ -1 114 284]
3
285
995
0
[ -1  32 388 466 953]
5
0
1
[ -1  32 388 466 953]
5
33
2
[ -1  32 388 466 953]
5
389
3
[ -1  32 388 466 953]
5
467
4
[ -1  32 388 466 953]
5
954
995
0
[ -1 805 860 929]
4
0
1
[ -1 805 860 929]
4
806
2
[ -1 805 860 929]
4
861
3
[ -1 805 860 929]
4
930
995
0
[ -1 761 814 853]
4
0
1
[ -1 761 814 853]
4
762
2
[ -1 761 814 853]
4
815
3
[ 

In [46]:
one_hot.sort_values("993", ascending=False)

-1    0    1    2    3    4    5    6    7    8  \
MANUAL ID                                                                       
No bird                   2463.0  6.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Aburria aburri              11.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Patagioenas picazuro         4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Pharomachrus auriceps        5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Pharomachrus antisianus     11.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...                          ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
Dubusia taeniata             5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Dryocopus lineatus          15.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Drymophila striaticeps       6.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Dromococcyx phasianellus     3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Zonotrichia capensis        12.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

                          ...   984  985  986  987  988   989  990  991   992  \
MANUAL ID                 ...                                                   
No bird                   ...  11.0  5.0  5.0  0.0  6.0  13.0  0.0  6.0  24.0   
Aburria aburri            ...   0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0   0.0   
Patagioenas picazuro      ...   0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0   0.0   
Pharomachrus auriceps     ...   0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0   0.0   
Pharomachrus antisianus   ...   0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0   0.0   
...                       ...   ...  ...  ...  ...  ...   ...  ...  ...   ...   
Dubusia taeniata          ...   0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0   0.0   
Dryocopus lineatus        ...   0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0   0.0   
Drymophila striaticeps    ...   0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0   0.0   
Dromococcyx phasianellus  ...   0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0   0.0   
Zonotrichia capensis      ...   0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0   0.0   

                          993  
MANUAL ID                      
No bird                   5.0  
Aburria aburri            0.0  
Patagioenas picazuro      0.0  
Pharomachrus auriceps     0.0  
Pharomachrus antisianus   0.0  
...                       ...  
Dubusia taeniata          0.0  
Dryocopus lineatus        0.0  
Drymophila striaticeps    0.0  
Dromococcyx phasianellus  0.0  
Zonotrichia capensis      0.0  

[476 rows x 995 columns]

In [67]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib qt 
# Make a 9x9 grid...
nrows, ncols = one_hot.shape

image = one_hot.to_numpy()/10

row_labels = one_hot.index
col_labels = range(ncols)
plt.matshow(image)
plt.xticks(range(ncols), col_labels)
plt.yticks(range(nrows), row_labels)
plt.show()

In [66]:
image
#https://stackoverflow.com/questions/10194482/custom-matplotlib-plot-chess-board-like-table-with-colored-cells

array([[1.1, 0. , 0. , ..., 0. , 0. , 0. ],
       [0.1, 0. , 0. , ..., 0. , 0. , 0. ],
       [0.1, 0. , 0. , ..., 0. , 0. , 0. ],
       ...,
       [0.7, 0. , 0. , ..., 0. , 0. , 0. ],
       [0.9, 0. , 0. , ..., 0. , 0.1, 0. ],
       [1.2, 0. , 0. , ..., 0. , 0. , 0. ]])